version: '3.7'

services:
  db:
    image: mysql
    ports:
      - "3306":"3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    restart: always
    volumes:
      - "./DB_INIT.sql:/docker-entrypoint-initdb.d/init.sql